#!/bin/bash
export PATH=".:$PATH"

export VERSION=`cat Dockerfile  | grep NORDVPN_BIN_VERSION= | sed 's/^ARG NORDVPN_BIN_VERSION=//'`

export X86="i386 amd64"
export ARM="armv7hf aarch64" 

manifestArch() {
  local options
  case $1 in
    i386)
      options="386" ;;
    amd64)
      options="amd64" ;;
    armv7hf)
      options="arm --variant v7" ;;
    aarch64)
      options="arm64 --variant v8" ;;
  esac
  echo ${options}
}

nordVpnArch(){
  case $1 in
    i386)
      echo "i386" ;;
    amd64)
      echo "amd64" ;;
    armv7hf)
      echo "armhf" ;;
    aarch64)
      echo "arm64" ;;
  esac
}
