#!/bin/bash
export PATH=".:$PATH"

export VERSION=`cat Dockerfile  | grep NORDVPN_BIN_VERSION= | sed 's/^ARG NORDVPN_BIN_VERSION=//'`
if [[ "${GIT_BRANCH}" != "master" ]]; then
  export VERSION=`echo ${VERSION}-${GIT_BRANCH}`
fi

export X86="amd64"
export ARM="armv7hf" 

manifestArch() {
  local options
  case $1 in
    i386)
      options="386" ;;
    amd64)
      options="amd64" ;;
    armv7hf)
      options="arm --variant v7" ;;
    aarch64)
      options="arm64 --variant v8" ;;
  esac
  echo ${options}
}

