#!/bin/bash

DOCKER_VERSION=19.03.5
DOCKER_MD5SUM=314f69b24af65fb486042c5ffb13da67

echo "**** Updating docker ****"
curl "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" | gunzip | tar -x --strip-components 1 docker/docker
if ! echo "${DOCKER_MD5SUM} docker" | md5sum --check --status ; then
  echo "Hash not match:"
  md5sum --binary docker
  exit 1
fi

echo "**** Enabling experimental mode ****"
mkdir -p ~/.docker
echo "{'auths': ${DOCKERCFG}, 'experimental': 'enabled'}" | tr "'" '"' > ~/.docker/config.json
