#!/bin/bash

DOCKER_VERSION=18.09.4
DOCKER_MD5SUM=17a327d2871874892b3b3d7532d7975c

echo "**** Updating docker ****"
curl "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" | gunzip | tar -x --strip-components 1 docker/docker
if ! echo "${DOCKER_MD5SUM} docker" | md5sum --check --status ; then
  echo "Hash not match:"
  md5sum --binary docker
  exit 1
fi

echo "**** Enabling experimental mode ****"
mkdir -p ~/.docker
echo "{'auths': ${DOCKERCFG}, 'experimental': 'enabled'}" | tr "'" '"' > ~/.docker/config.json